# Generated by Django 3.2 on 2022-05-24 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ekklesia_shared', '__first__'),
        ('ekklesia_auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('comments', models.CharField(max_length=500, null=True)),
                ('insert_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(null=True)),
                ('activity_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekklesia_shared.activitytype')),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_insert_user', to='ekklesia_auth.customuser')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_update_user', to='ekklesia_auth.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('home_phone', models.CharField(max_length=10, null=True)),
                ('cell_phone', models.CharField(max_length=10, null=True)),
                ('is_local_member', models.BooleanField()),
                ('birth_date', models.DateField(null=True)),
                ('conversion_date', models.DateField(null=True)),
                ('baptism_date', models.DateField(null=True)),
                ('contact_image', models.ImageField(null=True, upload_to='')),
                ('is_active', models.BooleanField()),
                ('insert_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(null=True)),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_insert_user', to='ekklesia_auth.customuser')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_update_user', to='ekklesia_auth.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateTimeField()),
                ('comments', models.CharField(max_length=500, null=True)),
                ('insert_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ekklesia_main.activity')),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movement_insert_user', to='ekklesia_auth.customuser')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movement_update_user', to='ekklesia_auth.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='MovementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_quantity', models.FloatField()),
                ('comments', models.CharField(max_length=500, null=True)),
                ('insert_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekklesia_shared.asset')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ekklesia_main.contact')),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movement_detail_insert_user', to='ekklesia_auth.customuser')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekklesia_main.movement')),
                ('movement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekklesia_shared.movementtype')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movement_detail_update_user', to='ekklesia_auth.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('insert_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(null=True)),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ministry_insert_user', to='ekklesia_auth.customuser')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ministry_update_user', to='ekklesia_auth.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='MemberMinistryPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekklesia_main.contact')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekklesia_main.ministry')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekklesia_shared.position')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=500, null=True)),
                ('insert_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekklesia_main.activity')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ekklesia_main.contact')),
                ('entity_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekklesia_shared.entitytype')),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_assistant_insert_user', to='ekklesia_auth.customuser')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_assistant_update_user', to='ekklesia_auth.customuser')),
            ],
        ),
    ]
