# Generated by Django 3.2 on 2022-05-25 22:18

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ekklesia_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('insert_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(null=True)),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='position_insert_user', to='ekklesia_auth.customuser')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='position_update_user', to='ekklesia_auth.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='MovementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('insert_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(null=True)),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movement_type_insert_user', to='ekklesia_auth.customuser')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movement_type_update_user', to='ekklesia_auth.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('insert_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(null=True)),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entity_type_insert_user', to='ekklesia_auth.customuser')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entity_type_update_user', to='ekklesia_auth.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='ekklesia_shared.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('insert_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(null=True)),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_insert_user', to='ekklesia_auth.customuser')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_update_user', to='ekklesia_auth.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('insert_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(null=True)),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_type_insert_user', to='ekklesia_auth.customuser')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_type_update_user', to='ekklesia_auth.customuser')),
            ],
        ),
    ]
