# Generated by Django 3.2 on 2022-05-25 23:53

from django.db import migrations


class Migration(migrations.Migration):\

    def add_entity_types(apps, schema_editor):
        global User
        User = apps.get_model('auth', 'User').objects.get(username='admin')
        EntityType = apps.get_model('ekklesia_shared', 'EntityType')
        EntityType.objects.update_or_create(alias="PERSON", defaults={'alias': 'PERSON', 'name': 'Persona', 'description': 'Persona', 'is_active': 'True', 'insert_user': User})
        EntityType.objects.update_or_create(alias="CHURCH", defaults={'alias': 'CHURCH', 'name': 'Iglesia', 'description': 'Iglesia', 'is_active': 'True', 'insert_user': User})
        EntityType.objects.update_or_create(alias="MINISTRY", defaults={'alias': 'MINISTRY', 'name': 'Ministerio', 'description': 'Ministerio', 'is_active': 'True', 'insert_user': User})
        EntityType.objects.update_or_create(alias="OTHER", defaults={'alias': 'OTHER', 'name': 'Otro', 'description': 'Otro', 'is_active': 'True', 'insert_user': User})

    def add_activity_types(apps, schema_editor):
        ActivityType = apps.get_model('ekklesia_shared', 'ActivityType')
        ActivityType.objects.update_or_create(alias="CULT", defaults={'alias': 'CULT', 'name': 'Culto', 'description': 'Culto', 'is_active': 'True', 'insert_user': User})
        ActivityType.objects.update_or_create(alias="CAMPAIGN", defaults={'alias': 'CAMPAIGN', 'name': 'Campaña', 'description': 'Campaña', 'is_active': 'True', 'insert_user': User})
        ActivityType.objects.update_or_create(alias="MEETING", defaults={'alias': 'MEETING', 'name': 'Reunión', 'description': 'Reunión', 'is_active': 'True', 'insert_user': User})
        ActivityType.objects.update_or_create(alias="VIGIL", defaults={'alias': 'VIGIL', 'name': 'Vigilia', 'description': 'Vigilia', 'is_active': 'True', 'insert_user': User})
        ActivityType.objects.update_or_create(alias="OTHER", defaults={'alias': 'OTHER', 'name': 'Otro', 'description': 'Otro', 'is_active': 'True', 'insert_user': User})

    def add_positions(apps, schema_editor):
        Position = apps.get_model('ekklesia_shared', 'Position')
        Position.objects.update_or_create(alias="PRESIDENT", defaults={'alias': 'PRESIDENT', 'name': 'Presidente', 'description': 'Presidente', 'is_active': 'True', 'insert_user': User})
        Position.objects.update_or_create(alias="SECRETARY", defaults={'alias': 'SECRETARY', 'name': 'Secretario/a', 'description': 'Secretario/a', 'is_active': 'True', 'insert_user': User})
        Position.objects.update_or_create(alias="VICEPRESIDENT", defaults={'alias': 'VICEPRESIDENT', 'name': 'Vice Presidente', 'description': 'Vice Presidente', 'is_active': 'True', 'insert_user': User})
        Position.objects.update_or_create(alias="TREASURER", defaults={'alias': 'TREASURER', 'name': 'Tesorero/a', 'description': 'Tesorero/a', 'is_active': 'True', 'insert_user': User})
        Position.objects.update_or_create(alias="OTHER", defaults={'alias': 'OTHER', 'name': 'Otro', 'description': 'Otro', 'is_active': 'True', 'insert_user': User})

    def add_movement_types(apps, schema_editor):
        MovementType = apps.get_model('ekklesia_shared', 'MovementType')
        MovementType.objects.update_or_create(alias="IN", defaults={'alias': 'IN', 'name': 'Entrada', 'description': 'Entrada', 'is_active': 'True', 'insert_user': User})
        MovementType.objects.update_or_create(alias="OUT", defaults={'alias': 'OUT', 'name': 'Salida', 'description': 'Salida', 'is_active': 'True', 'insert_user': User})

    def add_assets(apps, schema_editor):
        Asset = apps.get_model('ekklesia_shared', 'Asset')
        Asset.objects.update_or_create(alias="CHAIR", defaults={'alias': 'CHAIR', 'name': 'Silla', 'description': 'Silla', 'is_active': 'True', 'insert_user': User})
        Asset.objects.update_or_create(alias="OFFERING", defaults={'alias': 'OFFERING', 'name': 'Ofrenda', 'description': 'Ofrenda', 'is_active': 'True', 'insert_user': User})
        Asset.objects.update_or_create(alias="TITHE", defaults={'alias': 'TITHE', 'name': 'Diezmo', 'description': 'Diezmo', 'is_active': 'True', 'insert_user': User})
        Asset.objects.update_or_create(alias="EQUIPMENT", defaults={'alias': 'EQUIPMENT', 'name': 'Equipo', 'description': 'Equipo', 'is_active': 'True', 'insert_user': User})
        Asset.objects.update_or_create(alias="PAYMENT", defaults={'alias': 'PAYMENT', 'name': 'Payment', 'description': 'Payment', 'is_active': 'True', 'insert_user': User})
        Asset.objects.update_or_create(alias="OTHER", defaults={'alias': 'OTHER', 'name': 'Otro', 'description': 'Otro', 'is_active': 'True', 'insert_user': User})

    dependencies = [
        ('ekklesia_shared', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(add_entity_types),
         migrations.RunPython(add_activity_types),
         migrations.RunPython(add_positions),
         migrations.RunPython(add_movement_types),
         migrations.RunPython(add_assets),
    ]
